apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento-app
  template:
    metadata:
      labels:
        app: magento-app
    spec:
      containers:
      - name: php-fpm
        image: IMAGE_MAGENTO
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: src-volume
          mountPath: /var/www/
      volumes:
      - name: src-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: magento-app
spec:
  selector:
    app: magento-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
