# Đơn giản hóa nhất có thể để triển khai Magento lên GKE (hoàn chỉnh)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento-app
  template:
    metadata:
      labels:
        app: magento-app
    spec:
      containers:
        - name: magento
          image: gcr.io/enterprise-452702/techworld-magento:latest
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: magento-app
spec:
  selector:
    app: magento-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento-nginx
  template:
    metadata:
      labels:
        app: magento-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: magento.conf
      volumes:
        - name: nginx-config
          configMap:
            name: magento-nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  name: magento-nginx
spec:
  selector:
    app: magento-nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
